from enum import Enum

class AlarmRole(str, Enum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    USER = "USER"
    SERVICE = "SERVICE"
class UserRole(str, Enum):
    ADMIN = "ADMIN"
    USER = "USER"
    SERVICE = "SERVICE"

class AlarmStatus(str, Enum):
    ARMED = "ARMED"
    DISARMED = "DISARMED"
    TRIGGERED = "TRIGGERED"
    ARMING = "ARMING"
    DISARMING = "DISARMING"
    UNKNOWN = "UNKNOWN"   
    ACTIVATED = "ACTIVATED" 

class SensorStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    UNKNOWN = "UNKNOWN"

class SensorType(str, Enum):
    LDR = "LDR"
    DHT11 = "DHT11"
    PIR = "PIR"
    TEMPERATURE = "TEMPERATURE"
    HUMIDITY = "HUMIDITY"

class DeviceType(str, Enum):
    SENSOR = "SENSOR"
    MOTOR = "MOTOR"
    RGB_LED = "RGB_LED"
    BUZZER = "BUZZER"
    LED = "LED"
    LCD = "LCD"
    CAMERA = "CAMERA"
    SERVO = "SERVO"

class ConnectionType(str, Enum):
    GPIO = "GPIO"
    I2C = "I2C"
    SPI = "SPI"
    USB = "USB"
    ETHERNET = "ETHERNET"
    WIFI = "WIFI"
    CSI = "CSI"

class AlarmEventType(str, Enum):
    ALARM_ARMED = "ALARM_ARMED"
    ALARM_DISARMED = "ALARM_DISARMED"
    ALARM_TRIGGERED = "ALARM_TRIGGERED"
    ALARM_ARMING = "ALARM_ARMING"
    MOTION_DETECTED = "MOTION_DETECTED"
    TEMPERATURE_TRESHOLD = "TEMPERATURE_TRESHOLD"
    HUMIDITY_TRESHOLD = "HUMIDITY_TRESHOLD"
    CAMERA_MOTION = "CAMERA_MOTION"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    DOOR_OPENED = "DOOR_OPENED"
    DOOR_CLOSED = "DOOR_CLOSED"
    GATE_OPENED = "GATE_OPENED"
    GATE_CLOSED = "GATE_CLOSED"
    ALARM_ACTIVATED = "ALARM_ACTIVATED"

class NotificationType(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    ALERT = "ALERT"
    SYSTEM = "SYSTEM"

class MotorDirection(str, Enum):
    FORWARD = "FORWARD"
    BACKWARD = "BACKWARD"

class MessageEventType(str, Enum):
    
    CONNECTED = "CONNECTED"

    DISCONNECTED = "DISCONNECTED"

    ALARM_STATUS_CHANGED = "ALARM_STATUS_CHANGED"

    SENSOR_UPDATED = "SENSOR_UPDATED"

    DEVICE_STATE_CHANGED = "DEVICE_STATE_CHANGED"

    USER_ADDED_TO_ALARM = "USER_ADDED_TO_ALARM"

    USER_REMOVED_FROM_ALARM = "USER_REMOVED_FROM_ALARM"

    SETTINGS_UPDATED = "SETTINGS_UPDATED"

    NOTIFICATION_CREATED = "NOTIFICATION_CREATED"

    ERROR = "ERROR"

class MQTTMessageType(str, Enum):
    SENSOR = "sensor"
    STATE = "state"
    EVENT = "event"
    HEARTBEAT = "heartbeat"