services:
  postgres:
    image: postgres:17
    container_name: alarm-postgres

    environment:
      POSTGRES_USER: alarm
      POSTGRES_PASSWORD: alarm_password
      POSTGRES_DB: alarm_db

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  backend:
    build: .
    container_name: alarm-backend

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      - postgres
      - redis

    restart: unless-stopped

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  redis:
    image: redis:7-alpine
    container_name: alarm-redis
    ports:
      - "6379:6379"
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: alarm-mosquitto
    restart: unless-stopped

    ports:
      - "1883:1883"

    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "$SYS/broker/version", "-C", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  postgres_data:
