"""alarmevent model message changed to nullable

Revision ID: 0a69382c5503
Revises: 885bfe2571c0
Create Date: 2026-07-16 10:26:29.730448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a69382c5503'
down_revision: Union[str, Sequence[str], None] = '885bfe2571c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
