"""State in  devices table changed to json type

Revision ID: 182c27eaf8b4
Revises: 449104d10d45
Create Date: 2026-08-01 18:08:12.255955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '182c27eaf8b4'
down_revision: Union[str, Sequence[str], None] = '449104d10d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
