"""Relations with alarms added to other models

Revision ID: 5695f9cf5260
Revises: ca7f42d9fef8
Create Date: 2026-07-21 14:26:56.648700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5695f9cf5260'
down_revision: Union[str, Sequence[str], None] = 'ca7f42d9fef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_plates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alarm_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'alarms', ['alarm_id'], ['id'])

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alarm_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_sensors_alarm_id'), ['alarm_id'], unique=False)
        batch_op.create_foreign_key(None, 'alarms', ['alarm_id'], ['id'])

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alarm_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'alarms', ['alarm_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('alarm_id')

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sensors_alarm_id'))
        batch_op.drop_column('alarm_id')

    with op.batch_alter_table('car_plates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('alarm_id')

    # ### end Alembic commands ###
