"""added car_plates module and model

Revision ID: 6bfd69c86a7c
Revises: 59e0bdbd7117
Create Date: 2026-07-18 18:05:42.415661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfd69c86a7c'
down_revision: Union[str, Sequence[str], None] = '59e0bdbd7117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_plates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=7), nullable=False),
    sa.Column('owner_name', sa.String(length=50), nullable=True),
    sa.Column('auto_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car_plates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_plates_plate_number'), ['plate_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_plates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_plates_plate_number'))

    op.drop_table('car_plates')
    # ### end Alembic commands ###
