"""cascade added to clients-alarm relation

Revision ID: 847326a5343c
Revises: e3b16b325969
Create Date: 2026-08-06 13:43:22.453569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847326a5343c'
down_revision: Union[str, Sequence[str], None] = 'e3b16b325969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('clients_alarm_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'alarms', ['alarm_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('clients_alarm_id_fkey'), 'alarms', ['alarm_id'], ['id'])

    # ### end Alembic commands ###
