"""All tables added

Revision ID: 885bfe2571c0
Revises: 64d3cb808f39
Create Date: 2026-07-15 10:37:50.717604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885bfe2571c0'
down_revision: Union[str, Sequence[str], None] = '64d3cb808f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('connection_type', sa.Enum('GPIO', 'I2C', 'SPI', 'USB', 'ETHERNET', 'WIFI', 'CSI', name='connectiontype'), nullable=False),
    sa.Column('connection_identifier', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('SENSOR', 'MOTOR', 'RGB_LED', 'BUZZER', 'LED', 'LCD', 'CAMERA', 'SERVO', name='devicetype'), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=True)
    op.create_table('alarm_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('ALARM_ARMED', 'ALARM_DISARMED', 'ALARM_TRIGGERED', 'ALARM_ARMING', 'MOTION_DETECTED', 'TEMPERATURE_TRESHOLD', 'HUMIDITY_TRESHOLD', 'CAMERA_MOTION', 'SYSTEM_ERROR', 'DOOR_OPENED', 'DOOR_CLOSED', 'GATE_OPENED', 'GATE_CLOSED', name='alarmeventtype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('message', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_events_device_id'), 'alarm_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_alarm_events_timestamp'), 'alarm_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_alarm_events_user_id'), 'alarm_events', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('notification_type', sa.Enum('INFO', 'WARNING', 'ERROR', 'ALERT', name='notificationtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_timestamp'), 'notifications', ['timestamp'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_sensor_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_timestamp'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_alarm_events_user_id'), table_name='alarm_events')
    op.drop_index(op.f('ix_alarm_events_timestamp'), table_name='alarm_events')
    op.drop_index(op.f('ix_alarm_events_device_id'), table_name='alarm_events')
    op.drop_table('alarm_events')
    op.drop_index(op.f('ix_devices_name'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
