"""cascade added to relations with alarm

Revision ID: 9187cbce5c5d
Revises: 847326a5343c
Create Date: 2026-08-06 13:47:12.189243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9187cbce5c5d'
down_revision: Union[str, Sequence[str], None] = '847326a5343c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('alarm_events_alarm_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'alarms', ['alarm_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('car_plates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('car_plates_alarm_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'alarms', ['alarm_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('devices_alarm_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'alarms', ['alarm_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notifications_alarm_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'alarms', ['alarm_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sensors_alarm_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'alarms', ['alarm_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('settings_alarm_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'alarms', ['alarm_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('settings_alarm_id_fkey'), 'alarms', ['alarm_id'], ['id'])

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sensors_alarm_id_fkey'), 'alarms', ['alarm_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_alarm_id_fkey'), 'alarms', ['alarm_id'], ['id'])

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('devices_alarm_id_fkey'), 'alarms', ['alarm_id'], ['id'])

    with op.batch_alter_table('car_plates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('car_plates_alarm_id_fkey'), 'alarms', ['alarm_id'], ['id'])

    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('alarm_events_alarm_id_fkey'), 'alarms', ['alarm_id'], ['id'])

    # ### end Alembic commands ###
