"""client_type enum added

Revision ID: 9f55e967dcc7
Revises: a2c1247cc8e6
Create Date: 2026-08-05 12:59:35.506985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f55e967dcc7'
down_revision: Union[str, Sequence[str], None] = 'a2c1247cc8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('client_type', sa.Enum('RASPBERRY', 'ESP32', name='clienttype'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_client_id'), ['client_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_client_id'))

    op.drop_table('clients')
    # ### end Alembic commands ###
