"""pin_hash added to user

Revision ID: ae3bc65876d1
Revises: ed49a00cfc48
Create Date: 2026-07-17 09:24:56.464710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3bc65876d1'
down_revision: Union[str, Sequence[str], None] = 'ed49a00cfc48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('ALARM_ARMED', 'ALARM_DISARMED', 'ALARM_TRIGGERED', 'ALARM_ARMING', 'MOTION_DETECTED', 'TEMPERATURE_TRESHOLD', 'HUMIDITY_TRESHOLD', 'CAMERA_MOTION', 'SYSTEM_ERROR', 'DOOR_OPENED', 'DOOR_CLOSED', 'GATE_OPENED', 'GATE_CLOSED', name='alarmeventtype'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_hash', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pin_hash')

    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.Enum('ALARM_ARMED', 'ALARM_DISARMED', 'ALARM_TRIGGERED', 'ALARM_ARMING', 'MOTION_DETECTED', 'TEMPERATURE_TRESHOLD', 'HUMIDITY_TRESHOLD', 'CAMERA_MOTION', 'SYSTEM_ERROR', 'DOOR_OPENED', 'DOOR_CLOSED', 'GATE_OPENED', 'GATE_CLOSED', name='alarmeventtype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    op.create_table('_alembic_tmp_alarm_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('device_id', sa.INTEGER(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('message', sa.VARCHAR(length=100), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
