"""enum MessageEventType for WebSockets added

Revision ID: d1fb7848f945
Revises: e97e4a6cd41d
Create Date: 2026-07-27 09:33:17.664327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fb7848f945'
down_revision: Union[str, Sequence[str], None] = 'e97e4a6cd41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
