"""Pin moved to user_alarm

Revision ID: e3b16b325969
Revises: 9f55e967dcc7
Create Date: 2026-08-06 09:59:46.399281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b16b325969'
down_revision: Union[str, Sequence[str], None] = '9f55e967dcc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_alarm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_hash', sa.String(length=255), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pin_hash')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    with op.batch_alter_table('user_alarm', schema=None) as batch_op:
        batch_op.drop_column('pin_hash')

    # ### end Alembic commands ###
