"""Added tables alarms and join table user_alarm

Revision ID: e4e8c8e8b7e9
Revises: 6bfd69c86a7c
Create Date: 2026-07-21 10:55:29.843341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e8c8e8b7e9'
down_revision: Union[str, Sequence[str], None] = '6bfd69c86a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('ARMED', 'DISARMED', 'TRIGGERED', 'ARMING', 'ACTIVATED', 'UNKNOWN', name='alarmstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_alarm',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alarm_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'USER', 'SERVICE', name='alarmrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'alarm_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_alarm')
    op.drop_table('alarms')
    # ### end Alembic commands ###
